### PR TITLE
Use default formatting

### PR DESCRIPTION
**Pull request by hedgar2017**
I propose that we use the default `rustfmt` formatting to make working with the code easier for everybody.
We can also fix the linter errors and optimize the code later.

### CODE REVIEW

**Comment by hedgar2017** [comment]
Please, let me know if we are going to do that.

**Comment by playXE** [comment]
I think formatting s not that important. I'm focussing on optimizations and code generation now

**Comment by hedgar2017** [comment]
Common formatting is important if there are many people working with a project.
Most people are used to the de-facto Rust `rustfmt` standard.
Please, let me know if you are ok with using the default format or close the PR.

**Comment by playXE** [comment]
Can you please resolve conflicts?I'm going to merge that PR

**Comment by hedgar2017** [comment]
@playXE done! Please, merge.

**Pull request merged**
